application: mail-jetable
version: 3
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /Statics
  static_dir: Statics
- url: /_ah/mail/.+ 
  script: mail.py
- url: /.*
  script: mail.py